# Generated by Django 3.2.23 on 2023-12-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='personal_txt',
            new_name='pertxt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='proffesion_txt',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='post',
            name='proffesion',
        ),
    ]
