# Generated by Django 3.2.23 on 2023-12-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20231204_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='protxt',
        ),
    ]
